#ifndef COMMON_CONSTANTS_H
#define COMMON_CONSTANTS_H

#include "CommonIncludes.h"

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

//#define VALIDATION_LAYERS_ENABLED
#define VALIDATION_LAYERS_COUNT 1
const char* VALIDATION_LAYERS[VALIDATION_LAYERS_COUNT] = { "VK_LAYER_LUNARG_standard_validation" };

#define DEVICE_EXTENTIONS_COUNT 1
const char* DEVICE_REQUIRED_EXTENTIONS[DEVICE_EXTENTIONS_COUNT] = { VK_KHR_SWAPCHAIN_EXTENSION_NAME };

#endif
